struct ObjectPackage
{
    //goal bounds
    float goal_low_x;
    float goal_low_y;
    float goal_high_x;
    float goal_high_y;
    //Di bounds
    float Di_low_x;
    float Di_low_y;
    float Di_high_x;
    float Di_high_y;
    //robot bounds
    float robot_low_x;
    float robot_low_y;
    float robot_high_x;
    float robot_high_y;

};