name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run : |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libopencv-dev libboost-all-dev xorg-dev libglu1-mesa-dev
      - name : Install Box2D v2.4.1
        run : |
          cd ..
          git clone https://github.com/glafratta/box2d.git
          cd box2d
          cmake .
          sudo make install
      - name : Build
        shell: bash
        run : sh build.sh
      - name : Test
        run: ctest
